version: '3'

services:
  user:
    build: ./user
    mem_limit: 512m
    ports:
      - "8082:8082"
    environment:
      DB_URL: jdbc:mysql://user_db:3306/user?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: 1234
    restart: always
    depends_on:
      user_db:
        condition: service_healthy
  auth-server:
    build: ./auth-server
    mem_limit: 512m
    ports:
      - "8083:8083"
    restart: always
  api-gateway:
    build: ./api-gateway
    mem_limit: 512m
    ports:
      - "8084:8084"
    restart: always
  user_db:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: user
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10