server:
  port: 8761
eureka:
  client:
    register-with-eureka: false # Don't register yourself as a client
    fetch-registry: false       # Don't fetch the registry (you're the server)
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Eureka dashboard URL
spring:
  application:
    name: eureka-server